[2021-02-09 14:33:38,724] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.run_spider_goods 2021-02-09T11:33:02.348675+00:00 [queued]>
[2021-02-09 14:33:38,737] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.run_spider_goods 2021-02-09T11:33:02.348675+00:00 [queued]>
[2021-02-09 14:33:38,737] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 14:33:38,737] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2021-02-09 14:33:38,737] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 14:33:38,753] {taskinstance.py:900} INFO - Executing <Task(BashOperator): run_spider_goods> on 2021-02-09T11:33:02.348675+00:00
[2021-02-09 14:33:38,757] {standard_task_runner.py:53} INFO - Started process 2733 to run task
[2021-02-09 14:33:43,829] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: parse_goods.run_spider_goods 2021-02-09T11:33:02.348675+00:00 [running]> Maxims-MacBook-Air.local
[2021-02-09 14:33:48,863] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T
[2021-02-09 14:33:48,866] {bash_operator.py:105} INFO - Temporary script location: /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T/airflowtmpl5r3g4v0/run_spider_goods6jft_p0p
[2021-02-09 14:33:48,866] {bash_operator.py:115} INFO - Running command: #!/bin/bash

echo 1
cd parse_goods/scrapAmazon/scrapAmazon/spiders
scrapy crawl reviewsspider -o test.json
[2021-02-09 14:33:48,882] {bash_operator.py:122} INFO - Output:
[2021-02-09 14:33:48,896] {bash_operator.py:126} INFO - 1
[2021-02-09 14:33:48,897] {bash_operator.py:126} INFO - /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T/airflowtmpl5r3g4v0/run_spider_goods6jft_p0p: line 4: cd: parse_goods/scrapAmazon/scrapAmazon/spiders: No such file or directory
[2021-02-09 14:33:50,444] {bash_operator.py:126} INFO - Scrapy 2.4.1 - no active project
[2021-02-09 14:33:50,445] {bash_operator.py:126} INFO - 
[2021-02-09 14:33:50,445] {bash_operator.py:126} INFO - Unknown command: crawl
[2021-02-09 14:33:50,446] {bash_operator.py:126} INFO - 
[2021-02-09 14:33:50,446] {bash_operator.py:126} INFO - Use "scrapy" to see available commands
[2021-02-09 14:33:50,538] {bash_operator.py:130} INFO - Command exited with return code 2
[2021-02-09 14:33:50,547] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2021-02-09 14:33:50,560] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2021-02-09 14:33:53,878] {logging_mixin.py:112} INFO - [2021-02-09 14:33:53,876] {local_task_job.py:103} INFO - Task exited with return code 1
