[2021-02-09 12:11:15,315] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.run_spider_goods 2021-02-09T08:57:48.374621+00:00 [queued]>
[2021-02-09 12:11:15,335] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.run_spider_goods 2021-02-09T08:57:48.374621+00:00 [queued]>
[2021-02-09 12:11:15,335] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 12:11:15,335] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2021-02-09 12:11:15,336] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 12:11:15,348] {taskinstance.py:900} INFO - Executing <Task(BashOperator): run_spider_goods> on 2021-02-09T08:57:48.374621+00:00
[2021-02-09 12:11:15,351] {standard_task_runner.py:53} INFO - Started process 11052 to run task
[2021-02-09 12:11:20,474] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: parse_goods.run_spider_goods 2021-02-09T08:57:48.374621+00:00 [running]> Maxims-MacBook-Air.local
[2021-02-09 12:11:25,611] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T
[2021-02-09 12:11:25,613] {bash_operator.py:105} INFO - Temporary script location: /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T/airflowtmpa4tf9z7n/run_spider_goodswrny60d8
[2021-02-09 12:11:25,614] {bash_operator.py:115} INFO - Running command: #!/bin/bash

echo 1
scrapy crawl reviewsspider -o test.json
[2021-02-09 12:11:25,631] {bash_operator.py:122} INFO - Output:
[2021-02-09 12:11:25,644] {bash_operator.py:126} INFO - 1
[2021-02-09 12:11:27,174] {bash_operator.py:126} INFO - Scrapy 2.4.1 - no active project
[2021-02-09 12:11:27,175] {bash_operator.py:126} INFO - 
[2021-02-09 12:11:27,176] {bash_operator.py:126} INFO - Unknown command: crawl
[2021-02-09 12:11:27,177] {bash_operator.py:126} INFO - 
[2021-02-09 12:11:27,177] {bash_operator.py:126} INFO - Use "scrapy" to see available commands
[2021-02-09 12:11:27,274] {bash_operator.py:130} INFO - Command exited with return code 2
[2021-02-09 12:11:27,284] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2021-02-09 12:11:27,300] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=parse_goods, task_id=run_spider_goods, execution_date=20210209T085748, start_date=20210209T091115, end_date=20210209T091127
[2021-02-09 12:11:30,621] {logging_mixin.py:112} INFO - [2021-02-09 12:11:30,619] {local_task_job.py:103} INFO - Task exited with return code 1
